directories:
  output: release
  buildResources: build
appId: com.kurgu.app
productName: Kurgu
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - public/**/*
      - package.json
linux:
  target:
    - rpm
  category: Utility
  executableName: kurgu
electronVersion: 41.0.4
